# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='place_name',
        ),
    ]
