# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171104_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
