# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20171104_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_uri',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
