# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20171104_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='facebook',
            name='url',
            field=models.CharField(max_length=255, validators=[events.models.valid_facebook_url]),
        ),
    ]
