# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20171105_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
